### PR TITLE
ER図作成

### PR DESCRIPTION
**Pull request by kittyan1226**
ER図を以下の通り作成いたしました。恐れ入りますが、ご確認の程よろしくお願いいたします。

https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=%E6%87%B8%E8%B3%9E%E3%81%AB%E3%81%A3%E3%81%8DER%E5%9B%B3.drawio#R7V1bk6LItv41PE4HyZ1HrcueiNMd09Eze3bvpwpKKYvdKgZS3VXz608CmYqZiYJczZUTHTFCISr5rW%2Flumvm3eb9X0mwe%2F0SL8O1ZujLd8281wwD2bqH%2F5ed%2BSBndN8qzqySaEnOHU%2F8Gf0T0gvJ2bdoGe5PLkzjeJ1Gu9OTi3i7DRfpybkgSeJfp5e9xOvTT90Fq5A78eciWPNn%2FxMt09firGfrx%2FO%2Fh9HqlX4y0slfNgG9mJzYvwbL%2BNfJqfA9fYy3KfmKX8NkE2zDbYr%2F8iVIfoSJZj%2B8pmn2S2ea8Yj%2FvWRXf1rF8WodBrto%2F2kRb%2FDpxR5f8vgSbKJ19pxLN5qTG%2BGPMx808y6J47R4tXm%2FC9fZYtFlKL7TY8VfD88hye5b4w13v%2F38%2BPxDT7e%2F%2FzL%2FTr98WX11n38jd%2FkZrN%2FI8yXPJv2gDzxc4udPDsP1c%2Fzr4XhiHm6Xs2xR8d8evv0TJvFf8Zdgi3%2FzfJ8GSXr8G%2F79yz%2B25C2PEf5m5j2il5FjPfvre5R%2BJ3%2FLXv83O%2F%2FJJkf376XL7j%2FowTZNPr6XD0rvyg6Pb8uP6Pv4J0gexz5%2BSxbhmcdmEJnBX34VpmcuNAmuliegJgv0rzDehPgL4Qt%2BHaF8AOxrGcb0ZBKugzT6eSoMAQHs6nDDw2d8jaMcv4QATJfch4q%2Fo5%2Feovjp5F1lNDE3sqzTGzkGc6Pi0XA3wogIPkqX7bIL9g2%2BsHuCcvyiuCM9Kj3V46lcEhpIhcFJxbfwV5As99rDoza%2F0zxPe3A0z9Xm%2BIWnzU3Nf6B%2F8jkBwjyzy16mwXMuMznkCbGaGQ4xVaZBtMWsUOB%2BEa%2FXwW4f5ZcXZ16j9fJz8BG%2FpfRG9Gj%2BEr2Hy28Fr2bXYon7jG%2B2JyDPGIqKb%2FbnYB2ttvj1AoM%2B%2B8R5Eu7xd%2Fkc7FNyRaVY%2FAyTNHw%2Fi2O6aj6zahQdJZybSIBz22NgVIZ0adGbr6l5menoQuGfnkbB%2BhtWX8F2la%2FZ6ZJkz3WZxLu%2FqPhnJ3Ikh8nDz7BQIPnDx8R2F6%2FjbGW3cU5%2FBPD4A%2B05%2Fod%2F7l3GVDb%2BAnf4GB2P8b%2Fs8iS9i7f7NAmifDlCvFC%2Fwmyx5mm8I5%2BzDl%2Fo10jIw8xeP8dpivVR1bKexf7ltSZra9ZcWrOvlbW4lf36f03WNsa%2F9WWd66nXaLkMt4VIZruX4LjegqUUPv%2FDM2cXgxXEmuth1l6P8gI0fP7kZsen0vhuwRpjfxuk4Tx%2B2y733KJ2wMo2t85JzspP%2BF3TW27Ks8W18%2F0uWETb1efinQ6DB7sPPLxrVfJpeJ3io9btBgCIA5nixRvabijeGZviXW5lH6dI8TWfv1P7%2BctO6R63rm%2F7MMkI%2FbjRNjXP1GYOeYFPZi8MbV4%2Bc2nrPWE10DlmwNG%2Br2i%2FH9r3x6Z9%2BmGS8L5fewFk533E%2Bx03wfbtJVikb4lYASBWAczmoBRAffDIrAA2878%2BrO%2FPwcsX%2F%2B8%2F%2Fvz21V7%2Fb%2F4b4reHIDUAh426SqFSA9T223WhAsRry28RJ6wCLqzAGfRKrQPEv5vft%2B3TOAlPyd%2FW5jPNdzM3Oz7MXtw81XcJEnBcb%2FBbQsX13XC9PTbXGzWi0eNL%2BfVCXGAXHtPTZSyt6zra%2FjgNpuKtvJ3R%2FUzX5oj6eGy617fIXt%2Fz%2Fv3tM1AdUAUfeDoAdCy3Vx3gja4D%2BGiuZPv9Ar0AtQAfv93F%2B3RBIrjnMmsK6n%2BkyuDgAbqnzqEZdQWZ9E%2BPUJVEBbrgKQkVDe5JSRxSgcdTEu0cftNXEQ5QFcE7%2B%2FJkyacl%2FtiShvA1HyuJeW4uuPkLJ3MNzWyopF%2BBF3ikr2LBfZG%2BNTbp0xtLS%2Fo%2BTNI3ea9fEi7CaJc%2BLeKXlzBZBhtWARS7%2FkMqkHsaGzbza9zs%2FEzPlAQ%2B9KBGDqpgBU43mLwXUumGbnSDO7puaOcRnLxuMCsWQHrdwHsDg91uHS2CNIq3T8swWK6jbciqB1ubP2r%2BXU79c81%2FVMrgAo7gKQPeGamUQSfKwNRHVwa850%2ByEEKBXoDqgPf7FWXGT7skXr4tUjZ3aIZfP%2BSBBJRnkNqajxWAk7%2FAVgKCqgYq8ANODVhI6YG%2B9MCQdcEViyu9IiD4hacJLEHO9y6J%2FmGyRw8RZNh8XwkTgISv%2BL4nvh%2BySFi8tryDTzq6B8r2vHtv%2F%2Fa8ifb7zAv0EiebIOVyiB41v%2FD3uFkJQeYTutdmRv7iLk8mAqoKlCYgyeamYv5umH%2FIOuGKtZQ%2FaxRBTRsVmOjh%2B2v0HF2kfDdj95kPlOkrEQOO6i2eHRT1d0L91uj1wVY7B97keb%2FALjzat3jf3SZIfpx49717DcvQQ%2B7YmT3kSaA5zWfEb%2BX%2BfpDEXwUZeLyv%2BkL0xfuj1wpbfKr4BKW8hRAD7Qph8RncWZVYsH5axMvTGoAs4dPWHqwsxDvPc3x8Oy8FszNLYA41x6cKOeDo31Zlwn3R%2F%2BhlwnY7k27y9G8D9fbYvDkXLJdJuC%2B33rcyV37mwXcycsdYhEn0VRiBR%2FSq1LcnordHL%2FW1JS%2F1tYGW%2Btq8%2FRakKX5WUbw9TeF80Py80tfXM4cPUKpXBb7kQagC376ofvQCX5pAJC3VAy3wdficu3ziVZauvy2Sd1jS93MXDiF9j7j4CzXg5RVcQNWAquUlkBKYice6wP3ZUkC5xrRdgFGzMW1u7UJepH%2FSS%2F8ZfakE0JZd7VU%2BIyPVWVujq3vesruhuW1XrQhQW88R2HqlKm6Zxrd1CQt4Wl0Zd32x%2FejFGS5v3EmWoesANe9cUf%2BmG57L2T0CwBE50lXGbV9MPnqxBdJ541syKif4hcflSOcNbjqRc3oL3Oe8nSoEgONyw1VpVH1x%2Bfjj1QxX8kQqAl94VG64Z33kl1vmAW%2BpXYUbcArANRT%2F98X%2Fo5dRCJS7ZHv5Ar7w%2BF%2Bg2FXPjG4hBE4VmJbqmdEV9Y9eQmEKyuIl436CV3jkbwrK4lXTjDaIgcf19Hsorm%2FL9eMPTDM9NEE5biGmBTgBErvHW%2BOU2OPnLD2RdeycYfg8mTbz8BR1dODHqFWiChz5I71dewWlDc5og9ELLZDOJ1pJtvMnAIanIBBFkmqM3QYmABlfdcbujfFHn4%2BGaIWGrGFeAl%2BAfK%2FzEZxNuIknuLq98rhqa108CY93%2FJFpquWquDrzU1Wd3AE%2B6JA%2FT733iHYPLzOCLYCAYfTF6Z6qjbuaL7zmtXGixe1NX3vgauM8oLVxHu9oodOvbzPntru6uCpIVOt00%2BgWInVuN8iwUgsQs7czBC4wu6gOblBmNwUd7iTzvRG4wuNyU9CIjlZPsHtv53TLjTfh5TMgnXGVuAFH%2BB7vn1cKoBsFICqfG1QB0C8gqyfOA1oG7YvKoIuNvDgwX8cHoyL09cAFTkP47fz5SkM0LMobVkVIX5RRwBegkhAUZaRxwgTn7SxNC9P8g5cd%2BlAHWVSBBB7Zt5txpsi%2BYQXesGTfLowzfaqvWADpqZ4P4Rwc%2B5tg1dQSKK6Z0T%2BZ5OIZ1Jq8KliBUw5Wy9QepR0aFukNqh0sQXrPBAX9%2BhUg8IWnHyxBjzR4iVuVyw%2BOx5Fghn25X8trlFmKH0%2BbYIt3D5ucig28d8wSSfEKnOvkgs8g4kWc3WtzKysBmj3kA3LdvMO%2Bo7K9SpjzaLoujRnXLdVGTl9qACHQJmC71CIiWY2yvYbNzka8DSh5uhcBNDy1jxBvF56nefB5YJVYAZfcbSIPEOu3Mywusf7oHdFNJH0VJsErPJY%2FGBXQ%2B%2BhWIgAcdxum4u6uuHv0HuiGKT13E7zC4%2B5DfwY10KISA%2BDYG5k8KBSdd0Tn47dBRyafvSkZnxMEw%2BNzZBrc2t7%2B%2BLkegACQ1Pld3C7epwus6%2FenLdRcbV7umlOkZTzSJAyaujGrMZ8eUiCFrZqvG0fxe%2BN5wd4OkBpv6bM3K7LvJxNHsXgtLnscxYKq1S1eq1PuvlGV3mHEpAoV4FS8aTdqfHvj%2FN7WQjjP7%2BNHTGxe5iWz0ghe4fG5afOJjqp2vj1uwDE%2BstplzCoVMOXAC5J%2FaAmCOrQECYaWHAMv59wxICm%2FEicAKV%2F1S%2BmN8icQnKEVN7LWwBD8AmR8m3fYHZ04TJVkIy%2B8KpesCTFwysLSQZdS9KwsRh9oa%2BmS19MT%2FMJTFpbOV05ALJhUxRB088AT%2BSbYvr0Ei%2FQtCRO%2B3z1i%2FYazeQO%2FIaDAPd%2FvXsDrB2fQSehe788KUP3ur9fbduOG98Ll7dHGA9fxngAaniJHNt%2FzvkzcKnxfhYwzOt7pVsfXud0QUHEMyKTf0li7QPqCeP7ApO9I3tyGwBcgxTuC5jYlim%2B4NbfzLiU1kmsnrB56QBFAdcCbfHn%2F1H2r7qmQLTvRbMqhLTtHWXYtyGHqlp0Dz7JzoFp2Dm%2FZHfpbT2%2FFhzTpqiABUIerZI3e2H58k45uJ%2BQ16aDmarh8rkbO7We33tAtt%2BZZF5KyvmBgzf7teRPt91kN9kucbIKUqbl9zLCTdTF1M1hl4LrXZkb%2B4i5P%2B1F2XWXPUq9upnaPZp1gjA0gRd%2FShKgafjKZWlvBKBvZzTofamK%2BYAANR97KxKuCB7zMnJYzbW6c%2BVsaGBeYf%2FQqXCSYbDNByW%2BzAlDdd77AfcfyfMM9OnADsApK4HSCISjLDd9fo%2BfogtnnZqCZ%2BcraO2PtIV0QxRvY3DMElbmAlH4708KoquWcirlnCGpzJTf3CKDhbQMMi9%2B%2BE6oGb%2BRVggKgQm9nBtw437czMS7x%2FehGnmHxpsAEJb%2FNCrhQ2Z2PvxN2r7cPh23RVeIGngKok8gRLlch1bzh%2Bjn%2B9XA8UajlwlBD%2BFfPX9PNmmzbwu1yliQ5UB6%2B%2FRMm8V%2Fxl2D7Qc274982wXb5Rw6RJPul4fJwA%2FzrvhM85Af%2FzQ4%2B2fTw%2Fr38x%2FsPckSwgo%2Byb7QOnsP1PE6WYcIA8n9vmx357k7xfUtHxWPIfnsluMiplOq7yqdcYwzDwagTWnpJuA7S6OfpVzkDu6%2BZOj0C2tUZW9NloLaP35JFSN51hBl%2FIybz1EHMjYpnwd0Ir3XwUbqMqPvKL%2ByZp59jEXk5wr%2B4Y7fC4NZweZ8VhisQj9%2FyGK2pyOSXkWO9hQSE71H6nUoRfl16Fz46vik7oO%2BpD%2FgCLcWpu99%2Bfnz%2Boafb33%2BZf6dfvqy%2Bus%2BYYGtKBtIv22e9SobJemGulQzLPr2RoXu9SIbJSKBtDCIZNXaSJ5KxTaP041u%2BNvF2KH2xeEt%2B5gfXisC14nad6AgfNc2jvyw6NWZBDKpUPONK0Tm8kd6IDsrtWHRcNr8GWZ8M87y%2Ba%2F4WDzEC6rNv6UtGm27lJiCjVN5QX%2FJ2UYxqpILeyNaMgarrDyRFut7oe126npOfQbZ%2B1B4rNzFLsAiU41qHnmXYejY1D6lw1rmiNEfQc3DgojSMpcuUKK97s2XoxKvYX0ylKA3vG7jVlT2c5QHtLG94fOZBzs8qmFUFCXDlCYYHOnmhZSjlAtuPXpRmeO1afk4%2FmOVBTVXweLdrzu1nt97AI1hVYAHI%2BnwKQ7EzSIPVeeutGDtDW09jmlb23Bl7zq2rAvq059olNNy4hm9rO1QEvadjz%2FEOTOntucuBYTl1PkWWiLWVTVcFC3ja3QftwWtrUZxn%2FPFtOkFDgQlKfosV8KH66wR9Aw783nBTDtzSq4IQOF1g6rx%2Fr8DUAn%2FuKk6iC9G6056knkMxZnGjhtQkgRNT0GFDy3pdU7A31WHCngDUzuwwq7LupmIKmoIBQJKbgibUkUCmYCTQCa1%2FgLcHK7EBcA8A2gPYzhq5RPuj24OmznsAJRsMTQAMkOZpWp8kGRw9QAAemyPl3euNzQXNIwdmc8R792RjcwTUv2eiM%2F49eIxeBQOAjF7DLdNJPXEBAabopChI6bKU%2BJoqMr6Ic1k6Kh5HJ7UrqKoDxWjFKw4DuWuLV4ye6opdj%2FnCQxSXmEaNbc7AdcWTL45sV1dsopEr7rurK6atPmj5lNtPWRdbV2w5g0gGv0Usfs%2FTLomXb4v0dCjYDL9%2ByEM7KB83Z2u%2BnQdyVEVWjQw%2Bs65J0F8Gn2mofvLXbzOLZzXhsI3BR2hlD9sYQPvJmwa%2F0z%2Bl7hs1AzsM21RhA55ZaKhm8r3R%2FvhhG0PyZvIEvhBJng%2B3npJ8w%2B057Fy%2BShwBVAh8pLc8W%2FyJtQKzJ5eFEPHjbzp2XBmNbXL9qIdszFw%2FemeYu4e2BkpFg6PJGI0m7x2V3Wis0bpNzv2Eyfv7ztC%2BsiCrgAJvw2CCdhy2tV%2FO64DxLUiTdxzKlipiQnUUmryj8ITzb5Pke0ACQFJXbsHeSH38%2FD%2BTdwtKR%2BpQHYPmJccgQFpXzj3yJASzxzgsjDdUZPKpTxUPlRhAl6eN1Jh5N2hWoH9tVqDHdphnb9RVViCTKIN0e4jkpzrD125u9s5wk0fE4Ec3Kyb2tfMT2ORZpNeUk%2B6Q3HQ8iELyRSRbtbPA%2FYllgXcIZLOnGQZsb0NzEL6vMaBD7Xy45%2BYaNyMIzCAb27pWEHxWEGpmfXeGVbvt3kSNQmtasmBfriUctmTh%2Bm2798kv%2Feed3NYbpn4BDULpTo3KHlkovSzucZK%2Bxqt4G6zLMt%2Bh2Ph1Od%2B%2B7IEbdPPDOVzqSg1CjPzZPVm7yGC%2FMknlrvxm7BuQf%2FKGvmTLULLVVrbEMuPWFS5nasJlXy1c%2FoU79SZcdkPhoiXUPQtXjVkpvQrX%2Bb3jdVKUz3MmNyXhgfpic9lhVGP40qDSYDnMVqq2NByUFMWc1480sA5ca5BNmVsjVWiKDicBfEf2QVH3y2XjpUYZ3LCycf02jNEUFlsM27fp7Q7VQmNIbJ%2BMfe1yLzP2%2Fh%2FZrMJn8VIbeY6LhFuH4ZA36bjtkMgbE082y2TXankOTzVdL93hSQU4uyc82gH19varSL96QjybUcBq976sN88aZMMqY%2Fj0dND7yFkBXl2hqdPRr1%2F%2BtxhHtse2wqrP%2F%2BYp%2F3u6JfLLD6YNaoQ%2FFcpbobyuK6NOF%2BKeUU5cyIcSlM5Q7rqjolwwqDoJF2G0S58w9oJVuMkz0dkiZlq7PHdPq5nN%2FBpXmz3ktctuXj%2FvqJLlUmKtx8YtDRp2L%2BdNIxGa2QhLd7nvsGdRtyyP9SqcSdRbWXN5%2B6tsEMyilr1kGep0alMwnZon9ButduiwUvmKgdRep3ipdbtBAOMCYvqW9VMXmF5QmDw00%2FOmuWw1bFVTQuVndt4gfdtDLEiuQgA87qaxP8XdrblbUH88MHcLZkfLxt3FQwbI3YLJ0XRXDo6%2Bq0AAkL5Vk6De%2BBwZ4xO6%2FF2CapQwSUrovEst2O3W0SJIo3gLkNSbNwmSldRlzEoaOVTokGd6OVI4ek0lm5FxbaDQY4ozETeSp6viYov9IH2IJBK%2FbRKJqthsWrFZw3N2I0OmmHoAZNZMem5bpekOkl%2FlD5V5cpQM4WBCIk63P5nwcuEA9f5cFCJvYiVmx3zu1pUDCLH1%2F32lKR5GffUqR4dKCKnk6LxM5D8Bv8728NgWWZcET28geB2KFqq9dyt8ZCMmeRnMTsi8Nv%2BXG2WHDPZWnYkWowppT5qeJWt6E0Jl37zZI7f%2F6mzzhhA71LYvy4bdvTlDTM%2B1UI1UuhXWBTutytty6vrRDtxRP8eQNekEvlChvwR5%2Fkkyql%2BNkrquUTHsecf3v%2FdhwueZOuywnHn5jFxZpRedbEdosZipBMJvaGILr%2FJMubU%2BLyGXl7o6zbSxi7Xd2t50lunlFakvfBJFP8SPgndx33AmkjirtEs8nAmC2J3io9btBgiCIBXYrtrc1WT%2BSpoXDb%2Fpi%2BbFa9tOhU8%2Bpo2AhrQRr7630eLHNtiE7LbcoxMr8T8yw%2FKRnrlnC8JmOtDxqVVAgqcNavhhlTa4ShuIpuYMqw1qeALHl%2FIWQgw0YxUZ3LqGmyBaXxpnbObjjGHyffO8Vjn53uOxo%2Fi%2BG76v7cntjfAFDQMmKObXS3EBXniEL%2BgAsAv2%2B19xsmQ530fUGe9Tzn9ktQAmf5haoAo%2F4LRAjWZqSglcpwTs0ZWA3DoAaIUxn3a4x5%2F6JFADrjbD7D%2FTHjxtNjv6fJRiaA4qcHrB0nn2eI5WNNdjmngg5y5Ej4rEpCT%2BETIfej1qSMy%2FEjdsMo0AR02nKN8IjAReRfzs8eLcPIz08WEkiDLJCiPegalg1BWMBO5pWWHE%2B7wUjLqCkcjrJSuOePeawlFnOBIYzrLiSG2yr%2BjN6vDVVWAAw1v%2FkgCmHfE0BIwHBjBUJyvAtAGMgeAARm2RuwCMCwcw%2FF5YMUxjwBx6IwAADB%2FDXuJPVHBpAhc4HmRBwVIGlzTaKMichQxiIAPHWyyofFKQuYZl4HiG6WeqXUwbwFhwXMAmH5FSgGkOGDiuO5O3k7LMuFWYKMQ0QIwNxxVj8oaScsU0B4xgcJusgOFNJaWTmgMGju%2FO5A0lxTCNAePA8d2ZfL2AAkxzwMDx3pl8hoMCTHPAwPHdmdJmOAyZEuPBUUl0ey8fYIZkGA%2BOSrKU564LwMBRSZbBAUYFrJvCBU4oyVKO3i4Q48OJJVm8304h5grEwAkmWbzjTiGmOWIsOIngFm9Xq01MU4KBAxf6PZSR1KrQRIcTrbZ5sxo%2FSIWXZniBE6y2eataEobp09GLdGbCDyDAqEKTLgADJ7vB5vOnFGCaAwbBiSXZvCNGRauvQAycYJLNO2LUrvciXtjBm3BiSTafQKXwcgkvNlPKhgC1rLJVi5hrIHNwYMFr%2BWGrDKouEAOoIt9RGTFd9PyA44pxlO%2BuC4oBVC7rSOu8GxQxDpwUB4f33smS4jAoZFw4tpIjbx5Vr5DxWMjA8d85qgKyC5IB1CDRUSWQnZjXgDhG1UB2Yi0B2vsKhjwpxDS3luA4fWkEViGmFWI8OB4ZVzl9O7GVqNEJADG811cW83pYyPhwICNtCl6%2FDhkmQQaQee2qHmadIAZOMNLlXXgKMVcgBk5iuMu78CRBTL%2BlJ8ygNheQVpI2C69XjuEQA0grSZuFNyxi4Ggl%2BssVYlohBlDrO09Nxe4CMYD6xnjyuvAG3foCak7lqVnXXSAGASqK9FTqZkeYAbSXkdbvO2g7EATIjecpx29H1fpwICOt53dgyADazCjXbzeQgdPkwZPW99vrXoZr84DghAvoz5IPMr2yDA8ZONtfXyVwdtNMBs5exufdv6oJdHPAwLGXfOX87QYyEmx%2B8WESx2n58iTYvX6Jl2F2xf8D

### CODE REVIEW

**Comment by takyyk** [comment]
リンク先を見やすいようにissueに画像ではりつけてもらえるとです！
また各テーブルの説明をお願いいたします。

**Comment by kittyan1226** [comment]
早々にコメントいただきありがとうございます。ER図の貼り付けおよび各テーブルの説明は以下の通りです。改めてご確認の程宜しくお願いいたします。
**************
懸賞にっきER図

## usersテーブル
ユーザーの情報を管理するテーブル

## rewardsテーブル
懸賞の情報を管理するテーブル

## applicationsテーブル
応募の情報を管理するテーブル

## postcardsテーブル
懸賞ハガキの情報を管理するテーブル

## receiptsテーブル
レシートの情報を管理するテーブル

## manufacturersテーブル
メーカーの情報を管理するテーブル

## storesテーブル
店舗の情報を管理するテーブル

## target_productsテーブル
対象商品の情報を管理するテーブル。詳細な商品名だけでなく、「しょうゆ・つゆ類」のような分類名も混在する予定。

## prizesテーブル
賞品の情報を管理するテーブル

## submission_formatsテーブル
提出形式を管理するテーブル（プルダウンとかに利用）。web、ハガキなど５通りくらいで収まる。

## exhibitsテーブル
提出物を管理するテーブル（プルダウンとかに利用）レシート、バーコード、ポイントなど１０通りくらいで収まる。

## receipt_managementsテーブル
応募で利用したレシート（応募情報とレシートの紐づけ）を表すテーブル。１回の応募でレシートを複数利用することがある。

## application_history_managementsテーブル
応募履歴（懸賞情報と応募情報の紐付け）を管理するテーブル

## prize_tagsテーブル
賞品タグ（カテゴリー）を管理するテーブル。家電製品、商品券、食品系のようなタグ（カテゴリー）を用意。

## prize_categoriesテーブル
賞品と賞品タグ（カテゴリー）を紐づけるテーブル。例）賞品：BRUNOホットプレート→賞品タグ：家電製品

## manufacturer_target_productsテーブル
メーカーと対象商品を紐づけるテーブル。過去に似たような対象商品があった際、引用できるよう用意。

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
以下コメントになります。

---

■共通
・PKはidカラムで良いかと思います。

■Usersテーブル
・ログインで使用予定のgemは何を想定されていますでしょうか。そのgemに必要なカラムを一度確認しましょう。

■Rewardsテーブル
・テーブル名から何を行うテーブルなのかが分かる命名を付けましょう。sweepstakes_entriesなど、ChatGPTに聞いたりして適切な命名を付与しましょう。

■manufaturers, stores, target_products, exhibites, submission_formats, prizesprize_tagsテーブル
・各テーブルのカラム名がテーブル名と一致している状態です。`@store.store`といった形で呼び出すことになってしまうので、`@store.name`といったように読んだ際に具体的な情報が分かるような命名にしましょう。

一旦お返しします。

**Comment by kittyan1226** [comment]
レビューありがとうございます。以下の通り対応いたしました。
お手数おかけしますが、ご確認のほどよろしくお願いいたします。
*******
懸賞にっきER図_修正

### ◾️共通 ・PKはidカラムで良いかと思います。
→修正いたしました。

### ◾️Usersテーブル ・ログインで使用予定のgemは何を想定されていますでしょうか。そのgemに必要なカラムを一度確認しましょう。
→「devise」のユーザー認証機能を想定しています。またユーザーの新規登録完了後に「ActionMailer」を使って登録完了メールを送信できるようにしたいと考えています。

### ◾️Rewardsテーブル ・テーブル名から何を行うテーブルなのかが分かる命名を付けましょう。sweepstakes_entriesなど、ChatGPTに聞いたりして適切な命名を付与しましょう。
→”Sweepstake_details（懸賞詳細）”テーブルに変更いたしました。


### ◾️manufacturers, stores, target_products, exhibits, submission_formats, prizes, prize_tagsテーブル ・各テーブルのカラム名がテーブル名と一致している状態です。@store.storeといった形で呼び出すことになってしまうので、@store.nameといったように読んだ際に具体的な情報が分かるような命名にしましょう。
→ご指摘ありがとうございます。テーブル名とカラム名が一致しないように修正いたしました（計7テーブル）。

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
以下コメントになります。

---

■Usersテーブル
・ログインで使用予定のgemは何を想定されていますでしょうか。そのgemに必要なカラムを一度確認しましょう。（確認してください）

■postcardsテーブル
・postcard_imagte：命名に対して「懸賞ハガキリンク」とありますが...どちらが正確なのでしょうか。imageは画像等をイメージしますが...適切な形に修正してください。（receiptsテーブルのreceipt_image等も同様）

■prize_tagsテーブル
・tag_name：nameで良いかと。

■applicationsテーブル
・テーブル名の命名を適切にしましょう。

■共通
・テーブル名、カラム名はそれを読んでどういった値が入るものなのか、どういったリソースなのかがイメージできるものにしてください。

一旦お返しします。

**Comment by kittyan1226** [comment]
早々に回答いただきありがとうございます。以下の通り対応いたしました。（主な修正は赤）
お忙しいところ恐れ入りますが、再度ご確認のほどよろしくお願いいたします。
***********
懸賞にっきER図_修正２

#### ■Usersテーブル ログインで使用予定のgemは何を想定されていますでしょうか。そのgemに必要なカラムを一度確認しましょう。（確認してください）
→失礼いたしました。改めて確認し、Devise Gemに必要なカラムを追加いたしました。

#### ■postcardsテーブル postcard_image：命名に対して「懸賞ハガキリンク」とありますが...どちらが正確なのでしょうか。imageは画像等をイメージしますが...適切な形に修正してください。（receiptsテーブルのreceipt_image等も同様）
→画像のリンクで間違いないです。よってimageはそのままで、「懸賞ハガキ画像」などの日本語を修正いたしました。

#### ■prize_tagsテーブル tag_name：nameで良いかと。
→修正いたしました。

#### ■applicationsテーブル テーブル名の命名を適切にしましょう。
→contest_submissions（懸賞応募した内容）テーブルに変更いたしました。

#### ■共通 テーブル名、カラム名はそれを読んでどういった値が入るものなのか、どういったリソースなのかがイメージできるものにしてください。
→「懸賞応募」という単語を区別するために、応募前は「entry」、応募後は「submission」として変更いたしました。
その他「レシート印有無」がイメージしづらかったため「receipt_mark_needed」へ変更いたしました。

**Pull request merged**
